import { Product } from "./types";

// Flash design products with tattoo/merch aesthetic
export const flashDesigns: Product[] = [
  {
    id: 101,
    name: "Black Short",
    category: "shorts",
    price: 80,
    description: "Premium quality black short. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846845/blackshort_casse28pcs_grayclair40pcs_grayfonce116pcs_vert_36_noir186pcs-prix80dh_xnlqg7.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846845/blackshort_casse28pcs_grayclair40pcs_grayfonce116pcs_vert_36_noir186pcs-prix80dh_xnlqg7.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Casse", "Gray Clair", "Gray Fonce", "Vert", "Noir"],
    stock: {
      "Casse": 28,
      "Gray Clair": 40,
      "Gray Fonce": 116,
      "Vert": 36,
      "Noir": 186,
    },
    isNew: true,
    isSale: false,
    rating: 4.8,
    reviews: 56,
  },
  {
    id: 102,
    name: "Nike Short",
    category: "shorts",
    price: 65,
    description: "Nike short with premium quality fabric. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846844/nikeshort_reed36_green_28_mint_11_marron_40pcs_grayclair_32_bleu39pcs_grayfance71pcs_noir120pcs-prix65dh_rzwyiq.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846844/nikeshort_reed36_green_28_mint_11_marron_40pcs_grayclair_32_bleu39pcs_grayfance71pcs_noir120pcs-prix65dh_rzwyiq.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Reed", "Green", "Mint", "Marron", "Gray Clair", "Bleu", "Gray Fance", "Noir"],
    stock: {
      "Reed": 36,
      "Green": 28,
      "Mint": 11,
      "Marron": 40,
      "Gray Clair": 32,
      "Bleu": 39,
      "Gray Fance": 71,
      "Noir": 120,
    },
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 42,
  },
  {
    id: 103,
    name: "STWD Shirt",
    category: "shirts",
    price: 70,
    description: "STWD shirt available in blue, green, and brown.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785922185/50pcsinblue_green_brown_prix70dh_ac5pvh.png_rezifm.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785922185/50pcsinblue_green_brown_prix70dh_ac5pvh.png_rezifm.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Blue", "Green", "Brown"],
    stock: {
      "Blue": 50,
      "Green": 50,
      "Brown": 50,
    },
    isNew: false,
    isSale: false,
    rating: 4.5,
    reviews: 34,
  },
  {
    id: 104,
    name: "STWD Pants",
    category: "pants",
    price: 80,
    description: "STWD pants with premium quality. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846823/swdpentes_black60pcs_grayclair60pcs_vert24pcs_marron30pcs_grayfance30pcs_prix80dh_jummmi.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846823/swdpentes_black60pcs_grayclair60pcs_vert24pcs_marron30pcs_grayfance30pcs_prix80dh_jummmi.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "Gray Clair", "Vert", "Marron", "Gray Fance"],
    stock: {
      "Black": 60,
      "Gray Clair": 60,
      "Vert": 24,
      "Marron": 30,
      "Gray Fance": 30,
    },
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviews: 28,
  },
  {
    id: 105,
    name: "Green Short",
    category: "shorts",
    price: 80,
    description: "Green short in stock. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846788/greenshort_in_stock_36pcs_reed28pcs_grayfonce144pcs_casse40pcs_noir116pcs80dh_ufcu5l.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846788/greenshort_in_stock_36pcs_reed28pcs_grayfonce144pcs_casse40pcs_noir116pcs80dh_ufcu5l.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Reed", "Gray Fonce", "Casse", "Noir"],
    stock: {
      "Reed": 36,
      "Gray Fonce": 144,
      "Casse": 40,
      "Noir": 116,
    },
    isNew: false,
    isSale: false,
    rating: 4.4,
    reviews: 21,
  },
  {
    id: 106,
    name: "Ensemble STWD Brand",
    category: "ensemble",
    price: 125,
    description: "Ensemble STWD brand set. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846787/ensombleswdbrand_noir30pcs_grayfoncee30pcs_graydh4pcs-125dh_dskvgv.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846787/ensombleswdbrand_noir30pcs_grayfoncee30pcs_graydh4pcs-125dh_dskvgv.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Noir", "Gray Fonce", "Gray"],
    stock: {
      "Noir": 30,
      "Gray Fonce": 30,
      "Gray": 4,
    },
    isNew: true,
    isSale: false,
    rating: 4.9,
    reviews: 67,
  },
  {
    id: 107,
    name: "V2 Nike Short",
    category: "shorts",
    price: 60,
    description: "V2 Nike short. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846785/v2ofnikeshort_marron56pcs_casse_20pc_gray_clair20pcs_green24pcs_blue24pcs_grayfonce100pcs_black100pcs-60dh_jbjnzb.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846785/v2ofnikeshort_marron56pcs_casse_20pc_gray_clair20pcs_green24pcs_blue24pcs_grayfonce100pcs_black100pcs-60dh_jbjnzb.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Marron", "Casse", "Gray Clair", "Green", "Blue", "Gray Fonce", "Black"],
    stock: {
      "Marron": 56,
      "Casse": 20,
      "Gray Clair": 20,
      "Green": 24,
      "Blue": 24,
      "Gray Fonce": 100,
      "Black": 100,
    },
    isNew: false,
    isSale: false,
    rating: 4.2,
    reviews: 18,
  },
  {
    id: 108,
    name: "V2 Jordan Shorts",
    category: "shorts",
    price: 60,
    description: "V2 Jordan shorts. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846756/v2ofjordenshorts_marron56_casse20pcs_grayclair20pc_green24pcs_blue24pcs_grayfance100_black100pcsprix60dh_r8235v.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846756/v2ofjordenshorts_marron56_casse20pcs_grayclair20pc_green24pcs_blue24pcs_grayfance100_black100pcsprix60dh_r8235v.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Marron", "Casse", "Gray Clair", "Green", "Blue", "Gray Fance", "Black"],
    stock: {
      "Marron": 56,
      "Casse": 20,
      "Gray Clair": 20,
      "Green": 24,
      "Blue": 24,
      "Gray Fance": 100,
      "Black": 100,
    },
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviews: 31,
  },
  {
    id: 109,
    name: "Jordan Short",
    category: "shorts",
    price: 65,
    description: "Jordan short. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846751/jordenshort_green15pcs_bleu16pcs_rouge16pcs_grayclair_11pcs_mint8pcs_black44_marron11pcs_grayfonce28pcs-prix65dh_wzspsb.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846751/jordenshort_green15pcs_bleu16pcs_rouge16pcs_grayclair_11pcs_mint8pcs_black44_marron11pcs_grayfonce28pcs-prix65dh_wzspsb.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Green", "Bleu", "Rouge", "Gray Clair", "Mint", "Black", "Marron", "Gray Fonce"],
    stock: {
      "Green": 15,
      "Bleu": 16,
      "Rouge": 16,
      "Gray Clair": 11,
      "Mint": 8,
      "Black": 44,
      "Marron": 11,
      "Gray Fonce": 28,
    },
    isNew: false,
    isSale: false,
    rating: 4.5,
    reviews: 23,
  },
  {
    id: 110,
    name: "Jordan T-Shirt and Short Full Outfit",
    category: "ensemble",
    price: 100,
    description: "Jordan t-shirt and short full outfit. Premium quality set.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786277787/jorden_t-shirt_andshort_full_outfut_gsd8mc.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786277787/jorden_t-shirt_andshort_full_outfut_gsd8mc.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Default"],
    stock: {
      "Default": 100,
    },
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviews: 12,
  },
  {
    id: 111,
    name: "100 Pieces White Jersey T-Shirt and Short",
    category: "ensemble",
    price: 100,
    description: "100 pieces white jersey t-shirt and short set. Premium quality.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786277976/100pice_whiet_jurcye_t0shirt_and_short_db3xfj.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786277976/100pice_whiet_jurcye_t0shirt_and_short_db3xfj.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["White"],
    stock: {
      "White": 100,
    },
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 8,
  },
  {
    id: 112,
    name: "Baggy Pants 100 Pieces",
    category: "pants",
    price: 100,
    description: "Baggy pants, 100 pieces in stock. Premium quality.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786279136/bagy_pintes_100pice_h05e8b.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786279136/bagy_pintes_100pice_h05e8b.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Default"],
    stock: {
      "Default": 100,
    },
    isNew: true,
    isSale: false,
    rating: 4.5,
    reviews: 15,
  },
  {
    id: 113,
    name: "120 Pieces Full Outfit Pants and T-Shirt",
    category: "ensemble",
    price: 120,
    description: "120 pieces full outfit pants and t-shirt set. Premium quality.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786278977/120pice_full_outfit_pince_and_tishirt_e71o8w.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786278977/120pice_full_outfit_pince_and_tishirt_e71o8w.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Default"],
    stock: {
      "Default": 120,
    },
    isNew: true,
    isSale: false,
    rating: 4.8,
    reviews: 10,
  },
  {
    id: 114,
    name: "Zara Full Outfit T-Shirt and Short",
    category: "ensemble",
    price: 130,
    description: "Zara full outfit t-shirt and short set. Premium quality.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786280254/130dh_zara_full_outfit_t-shirt-short_ytnel3.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786280254/130dh_zara_full_outfit_t-shirt-short_ytnel3.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Default"],
    stock: {
      "Default": 130,
    },
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 9,
  },
  {
    id: 115,
    name: "Jordan Full Outfit T-Shirt & Short",
    category: "ensemble",
    price: 100,
    description: "Jordan full outfit t-shirt and short set. Premium quality.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786449008/100dh_jorden_full_outifit_t-shirt_short_heynm8.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786449008/100dh_jorden_full_outifit_t-shirt_short_heynm8.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Default"],
    stock: {
      "Default": 100,
    },
    isNew: true,
    isSale: false,
    rating: 4.5,
    reviews: 0,
  },
  {
    id: 116,
    name: "Jordan Pants",
    category: "pants",
    price: 90,
    description: "Jordan pants. Premium quality.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786449827/jordern_pentes_90dh_v2j85x.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786449827/jordern_pentes_90dh_v2j85x.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Reed", "Gray", "White", "Brown"],
    stock: {
      "Reed": 20,
      "Gray": 30,
      "White": 20,
      "Brown": 20,
    },
    isNew: true,
    isSale: false,
    rating: 4.5,
    reviews: 0,
  },
  {
    id: 117,
    name: "Jordan T-Shirt & Short Full Outfit",
    category: "ensemble",
    price: 100,
    description: "Jordan t-shirt and short full outfit. Premium quality.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786449999/jordern_tishort_and_short_fuuloutfit_100dh_trdnzu.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786449999/jordern_tishort_and_short_fuuloutfit_100dh_trdnzu.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Default"],
    stock: {
      "Default": 100,
    },
    isNew: true,
    isSale: false,
    rating: 4.5,
    reviews: 0,
  },
  {
    id: 118,
    name: "Sweat Pants",
    category: "pants",
    price: 110,
    description: "Premium sweat pants. Available in gray, reed, and blue.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786708206/swet_pentes_110dh_gray_reed_blue_zrhdtl.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786708206/swet_pentes_110dh_gray_reed_blue_zrhdtl.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Gray", "Reed", "Blue"],
    stock: {
      "Gray": 40,
      "Reed": 40,
      "Blue": 40,
    },
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviews: 0,
  },
  {
    id: 119,
    name: "T-Shirt",
    category: "shirts",
    price: 80,
    description: "Premium quality t-shirt. Available in blue, white, green, black, and gray.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786708834/t-shirt-blue-whiet-gree-black-gray_prix80dh_nemonp.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786708834/t-shirt-blue-whiet-gree-black-gray_prix80dh_nemonp.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Blue", "White", "Green", "Black", "Gray"],
    stock: {
      "Blue": 20,
      "White": 20,
      "Green": 20,
      "Black": 20,
      "Gray": 20,
    },
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 0,
  },
  {
    id: 120,
    name: "T-Shirt",
    category: "shirts",
    price: 95,
    description: "Premium quality t-shirt. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786967589/t-shirt_95dh_blue_cramel_whiet_black_u0rqkn.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786967589/t-shirt_95dh_blue_cramel_whiet_black_u0rqkn.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Blue", "Cramel", "White", "Black"],
    stock: {
      "Blue": 25,
      "Cramel": 25,
      "White": 25,
      "Black": 25,
    },
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviews: 0,
  },
  {
    id: 121,
    name: "Short",
    category: "shorts",
    price: 65,
    description: "Premium quality short. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786968636/short-black-blue-rinbo-65dh_ebdsz7.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786968636/short-black-blue-rinbo-65dh_ebdsz7.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "Blue", "Rainbow"],
    stock: {
      "Black": 30,
      "Blue": 30,
      "Rainbow": 30,
    },
    isNew: true,
    isSale: false,
    rating: 4.5,
    reviews: 0,
  },
  {
    id: 122,
    name: "T-Shirt",
    category: "shirts",
    price: 125,
    description: "Premium quality t-shirt. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786969114/t-shirt-black-whiet_125dh_rfqq4j.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786969114/t-shirt-black-whiet_125dh_rfqq4j.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "White"],
    stock: {
      "Black": 50,
      "White": 50,
    },
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 0,
  },
  {
    id: 123,
    name: "T-Shirt Type Sweet",
    category: "shirts",
    price: 80,
    description: "Sweet style t-shirt. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786969261/-t-shirt-type-sweet_blue_whiet_blue_sky_gray_80dh_ygvzb8.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1786969261/-t-shirt-type-sweet_blue_whiet_blue_sky_gray_80dh_ygvzb8.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Blue", "White", "Blue Sky", "Gray"],
    stock: {
      "Blue": 25,
      "White": 25,
      "Blue Sky": 25,
      "Gray": 25,
    },
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviews: 0,
  },
  {
    id: 124,
    name: "Nike Short",
    category: "shorts",
    price: 120,
    description: "Premium quality Nike short. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1787060754/short-nike-reed-gray-bluedark-120dh_ity4sq.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1787060754/short-nike-reed-gray-bluedark-120dh_ity4sq.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Reed", "Gray", "Blue Dark"],
    stock: {
      "Reed": 40,
      "Gray": 40,
      "Blue Dark": 40,
    },
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 0,
  },
  {
    id: 125,
    name: "T-Shirt",
    category: "shirts",
    price: 110,
    description: "Premium quality t-shirt. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1787061050/t-shirt_green_whiet_brown_black_110dh_gwxwda.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1787061050/t-shirt_green_whiet_brown_black_110dh_gwxwda.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Green", "White", "Brown", "Black"],
    stock: {
      "Green": 25,
      "White": 25,
      "Brown": 25,
      "Black": 25,
    },
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviews: 0,
  },
  {
    id: 126,
    name: "Black Nike Pants",
    category: "pants",
    price: 140,
    description: "Premium quality black Nike pants. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1787224327/black_pintes_nike_140dh_gray_black_light_green_bdmzjh.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1787224327/black_pintes_nike_140dh_gray_black_light_green_bdmzjh.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Gray", "Black", "Light Green"],
    stock: {
      "Gray": 40,
      "Black": 40,
      "Light Green": 40,
    },
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 0,
  },
  {
    id: 127,
    name: "Black Adidas T-Shirt",
    category: "shirts",
    price: 85,
    description: "Premium quality black Adidas t-shirt. Available in multiple colors.",
    image: "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1787224616/black_t-shirt_addidas_black_gray_whiet_85dh_vc0b4y.png",
    images: [
      "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1787224616/black_t-shirt_addidas_black_gray_whiet_85dh_vc0b4y.png",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "White"],
    stock: {
      "Black": 30,
      "Gray": 30,
      "White": 30,
    },
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviews: 0,
  },
];

export function getFlashDesignById(id: number): Product | undefined {
  return flashDesigns.find((p) => p.id === id);
}

export function getFlashDesignsByCategory(category: string): Product[] {
  if (category === "all" || !category) return flashDesigns;
  return flashDesigns.filter((p) => p.category === category);
}