import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "Classic Cotton T-Shirt",
    category: "men",
    price: 29.99,
    originalPrice: 39.99,
    description: "Premium quality cotton t-shirt with a relaxed fit. Perfect for everyday wear with exceptional comfort and breathability.",
    image: "https://picsum.photos/seed/tshirt1/600/800",
    images: [
      "https://picsum.photos/seed/tshirt1a/600/800",
      "https://picsum.photos/seed/tshirt1b/600/800",
      "https://picsum.photos/seed/tshirt1c/600/800",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Navy", "Gray"],
    isNew: false,
    isSale: true,
    rating: 4.5,
    reviews: 128,
  },
  {
    id: 2,
    name: "Slim Fit Denim Jacket",
    category: "men",
    price: 89.99,
    description: "Modern slim fit denim jacket crafted from premium selvedge denim. Features a classic design with a contemporary silhouette.",
    image: "https://picsum.photos/seed/jacket1/600/800",
    images: [
      "https://picsum.photos/seed/jacket1a/600/800",
      "https://picsum.photos/seed/jacket1b/600/800",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Light Blue", "Dark Blue", "Black"],
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 3,
    name: "Wool Blend Overcoat",
    category: "men",
    price: 199.99,
    originalPrice: 259.99,
    description: "Elegant wool blend overcoat with a tailored fit. Features a classic notched lapel and two-button closure.",
    image: "https://picsum.photos/seed/coat1/600/800",
    images: [
      "https://picsum.photos/seed/coat1a/600/800",
      "https://picsum.photos/seed/coat1b/600/800",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Charcoal", "Black", "Camel"],
    isNew: false,
    isSale: true,
    rating: 4.8,
    reviews: 56,
  },
  {
    id: 4,
    name: "Casual Linen Shirt",
    category: "men",
    price: 49.99,
    description: "Lightweight linen shirt perfect for summer. Features a relaxed fit with a classic collar and chest pocket.",
    image: "https://picsum.photos/seed/shirt1/600/800",
    images: [
      "https://picsum.photos/seed/shirt1a/600/800",
      "https://picsum.photos/seed/shirt1b/600/800",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Blue", "Beige", "Sage"],
    isNew: true,
    isSale: false,
    rating: 4.3,
    reviews: 201,
  },
  {
    id: 5,
    name: "Slim Chino Pants",
    category: "men",
    price: 59.99,
    description: "Modern slim fit chino pants made from stretch cotton twill. Comfortable and versatile for any occasion.",
    image: "https://picsum.photos/seed/chino1/600/800",
    images: [
      "https://picsum.photos/seed/chino1a/600/800",
      "https://picsum.photos/seed/chino1b/600/800",
    ],
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Khaki", "Navy", "Black", "Olive"],
    isNew: false,
    isSale: false,
    rating: 4.4,
    reviews: 167,
  },
  {
    id: 6,
    name: "Floral Summer Dress",
    category: "women",
    price: 69.99,
    originalPrice: 89.99,
    description: "Beautiful floral print dress with a flattering A-line silhouette. Features adjustable straps and a smocked bodice.",
    image: "https://picsum.photos/seed/dress1/600/800",
    images: [
      "https://picsum.photos/seed/dress1a/600/800",
      "https://picsum.photos/seed/dress1b/600/800",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Floral Blue", "Floral Pink", "Floral Yellow"],
    isNew: false,
    isSale: true,
    rating: 4.6,
    reviews: 245,
  },
  {
    id: 7,
    name: "Cashmere Sweater",
    category: "women",
    price: 129.99,
    description: "Luxuriously soft cashmere sweater with a relaxed fit. A timeless wardrobe essential for cooler months.",
    image: "https://picsum.photos/seed/sweater1/600/800",
    images: [
      "https://picsum.photos/seed/sweater1a/600/800",
      "https://picsum.photos/seed/sweater1b/600/800",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Black", "Burgundy", "Heather Gray"],
    isNew: true,
    isSale: false,
    rating: 4.9,
    reviews: 78,
  },
  {
    id: 8,
    name: "High-Waisted Jeans",
    category: "women",
    price: 79.99,
    description: "High-waisted skinny jeans with stretch denim for all-day comfort. Classic five-pocket design.",
    image: "https://picsum.photos/seed/jeans1/600/800",
    images: [
      "https://picsum.photos/seed/jeans1a/600/800",
      "https://picsum.photos/seed/jeans1b/600/800",
    ],
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31", "32"],
    colors: ["Light Wash", "Mid Wash", "Dark Wash", "Black"],
    isNew: false,
    isSale: false,
    rating: 4.5,
    reviews: 312,
  },
  {
    id: 9,
    name: "Silk Blouse",
    category: "women",
    price: 89.99,
    originalPrice: 119.99,
    description: "Elegant silk blouse with a relaxed drape. Features a hidden button placket and mother-of-pearl buttons.",
    image: "https://picsum.photos/seed/blouse1/600/800",
    images: [
      "https://picsum.photos/seed/blouse1a/600/800",
      "https://picsum.photos/seed/blouse1b/600/800",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Ivory", "Pink", "Lavender"],
    isNew: false,
    isSale: true,
    rating: 4.4,
    reviews: 134,
  },
  {
    id: 10,
    name: "Leather Moto Jacket",
    category: "women",
    price: 249.99,
    description: "Genuine leather moto jacket with asymmetrical zip closure. Features quilted shoulders and snap lapels.",
    image: "https://picsum.photos/seed/moto1/600/800",
    images: [
      "https://picsum.photos/seed/moto1a/600/800",
      "https://picsum.photos/seed/moto1b/600/800",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Brown", "Burgundy"],
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 45,
  },
  {
    id: 11,
    name: "Pleated Mini Skirt",
    category: "women",
    price: 54.99,
    description: "Chic pleated mini skirt in stretch fabric. Perfect for both casual and dressy occasions.",
    image: "https://picsum.photos/seed/skirt1/600/800",
    images: [
      "https://picsum.photos/seed/skirt1a/600/800",
      "https://picsum.photos/seed/skirt1b/600/800",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Plaid", "Gray"],
    isNew: true,
    isSale: false,
    rating: 4.2,
    reviews: 98,
  },
  {
    id: 12,
    name: "Graphic Hoodie",
    category: "men",
    price: 59.99,
    description: "Comfortable pullover hoodie with a bold graphic print. Made from heavyweight cotton fleece.",
    image: "https://picsum.photos/seed/hoodie1/600/800",
    images: [
      "https://picsum.photos/seed/hoodie1a/600/800",
      "https://picsum.photos/seed/hoodie1b/600/800",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Navy", "Forest Green"],
    isNew: false,
    isSale: false,
    rating: 4.6,
    reviews: 189,
  },
  {
    id: 13,
    name: "Kids Denim Overall",
    category: "kids",
    price: 44.99,
    description: "Adorable denim overalls for kids. Features adjustable straps and plenty of pockets for little treasures.",
    image: "https://picsum.photos/seed/overall1/600/800",
    images: [
      "https://picsum.photos/seed/overall1a/600/800",
      "https://picsum.photos/seed/overall1b/600/800",
    ],
    sizes: ["2T", "3T", "4T", "5", "6", "7", "8"],
    colors: ["Light Blue", "Dark Blue", "Pink"],
    isNew: false,
    isSale: false,
    rating: 4.3,
    reviews: 67,
  },
  {
    id: 14,
    name: "Kids Graphic Tee Pack",
    category: "kids",
    price: 24.99,
    originalPrice: 34.99,
    description: "Pack of 3 colorful graphic t-shirts for kids. Made from soft, durable cotton with fun prints.",
    image: "https://picsum.photos/seed/kidshirt1/600/800",
    images: [
      "https://picsum.photos/seed/kidshirt1a/600/800",
      "https://picsum.photos/seed/kidshirt1b/600/800",
    ],
    sizes: ["2T", "3T", "4T", "5", "6", "7", "8"],
    colors: ["Multi", "Dino Print", "Space Print"],
    isNew: true,
    isSale: true,
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 15,
    name: "Kids Raincoat",
    category: "kids",
    price: 39.99,
    description: "Waterproof raincoat with a fun animal print hood. Keeps little ones dry and stylish on rainy days.",
    image: "https://picsum.photos/seed/raincoat1/600/800",
    images: [
      "https://picsum.photos/seed/raincoat1a/600/800",
      "https://picsum.photos/seed/raincoat1b/600/800",
    ],
    sizes: ["2T", "3T", "4T", "5", "6"],
    colors: ["Yellow", "Frog Green", "Duck Orange"],
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviews: 112,
  },
  {
    id: 16,
    name: "Classic White Sneakers",
    category: "men",
    price: 74.99,
    description: "Timeless white leather sneakers with a cushioned sole. Versatile enough to pair with any outfit.",
    image: "https://picsum.photos/seed/sneakers1/600/800",
    images: [
      "https://picsum.photos/seed/sneakers1a/600/800",
      "https://picsum.photos/seed/sneakers1b/600/800",
    ],
    sizes: ["7", "8", "9", "10", "11", "12", "13"],
    colors: ["White", "Black", "Navy"],
    isNew: false,
    isSale: false,
    rating: 4.5,
    reviews: 423,
  },
];

export const categories = [
  { id: "all", name: "All", image: "https://picsum.photos/seed/all/600/400" },
  { id: "men", name: "Men", image: "https://picsum.photos/seed/men/600/400" },
  { id: "women", name: "Women", image: "https://picsum.photos/seed/women/600/400" },
  { id: "kids", name: "Kids", image: "https://picsum.photos/seed/kids/600/400" },
];

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all" || !category) return products;
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isNew || p.isSale).slice(0, 8);
}