import { Product } from "./types";

const cloudinaryImages = [
  "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846845/blackshort_casse28pcs_grayclair40pcs_grayfonce116pcs_vert_36_noir186pcs-prix80dh_xnlqg7.png",
  "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846844/nikeshort_reed36_green_28_mint_11_marron_40pcs_grayclair_32_bleu39pcs_grayfance71pcs_noir120pcs-prix65dh_rzwyiq.png",
  "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785922185/50pcsinblue_green_brown_prix70dh_ac5pvh.png_rezifm.png",
  "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846823/swdpentes_black60pcs_grayclair60pcs_vert24pcs_marron30pcs_grayfance30pcs_prix80dh_jummmi.png",
  "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846788/greenshort_in_stock_36pcs_reed28pcs_grayfonce144pcs_casse40pcs_noir116pcs80dh_ufcu5l.png",
  "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846787/ensombleswdbrand_noir30pcs_grayfoncee30pcs_graydh4pcs-125dh_dskvgv.png",
  "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846785/v2ofnikeshort_marron56pcs_casse_20pc_gray_clair20pcs_green24pcs_blue24pcs_grayfonce100pcs_black100pcs-60dh_jbjnzb.png",
  "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846756/v2ofjordenshorts_marron56_casse20pcs_grayclair20pc_green24pcs_blue24pcs_grayfance100_black100pcsprix60dh_r8235v.png",
  "https://res.cloudinary.com/dlfbj1ix5/image/upload/v1785846751/jordenshort_green15pcs_bleu16pcs_rouge16pcs_grayclair_11pcs_mint8pcs_black44_marron11pcs_grayfonce28pcs-prix65dh_wzspsb.png",
];

export const products: Product[] = [
  {
    id: 1,
    name: "Black Short",
    category: "shorts",
    price: 80,
    description: "Premium quality black short. Available in multiple colors.",
    image: cloudinaryImages[0],
    images: [cloudinaryImages[0]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Casse", "Gray Clair", "Gray Fonce", "Vert", "Noir"],
    stock: {
      "Casse": 28,
      "Gray Clair": 40,
      "Gray Fonce": 116,
      "Vert": 36,
      "Noir": 186,
    },
    isNew: false,
    isSale: false,
    rating: 4.5,
    reviews: 128,
  },
  {
    id: 2,
    name: "Nike Short",
    category: "shorts",
    price: 65,
    description: "Nike short with premium quality fabric. Available in multiple colors.",
    image: cloudinaryImages[1],
    images: [cloudinaryImages[1]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Reed", "Green", "Mint", "Marron", "Gray Clair", "Bleu", "Gray Fance", "Noir"],
    stock: {
      "Reed": 36,
      "Green": 28,
      "Mint": 11,
      "Marron": 40,
      "Gray Clair": 32,
      "Bleu": 39,
      "Gray Fance": 71,
      "Noir": 120,
    },
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 3,
    name: "STWD Shirt",
    category: "shirts",
    price: 70,
    description: "STWD shirt available in blue, green, and brown.",
    image: cloudinaryImages[2],
    images: [cloudinaryImages[2]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Blue", "Green", "Brown"],
    stock: {
      "Blue": 50,
      "Green": 50,
      "Brown": 50,
    },
    isNew: false,
    isSale: false,
    rating: 4.8,
    reviews: 56,
  },
  {
    id: 4,
    name: "STWD Pants",
    category: "pants",
    price: 80,
    description: "STWD pants with premium quality. Available in multiple colors.",
    image: cloudinaryImages[3],
    images: [cloudinaryImages[3]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "Gray Clair", "Vert", "Marron", "Gray Fance"],
    stock: {
      "Black": 60,
      "Gray Clair": 60,
      "Vert": 24,
      "Marron": 30,
      "Gray Fance": 30,
    },
    isNew: true,
    isSale: false,
    rating: 4.3,
    reviews: 201,
  },
  {
    id: 5,
    name: "Green Short",
    category: "shorts",
    price: 80,
    description: "Green short in stock. Available in multiple colors.",
    image: cloudinaryImages[4],
    images: [cloudinaryImages[4]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Reed", "Gray Fonce", "Casse", "Noir"],
    stock: {
      "Reed": 36,
      "Gray Fonce": 144,
      "Casse": 40,
      "Noir": 116,
    },
    isNew: false,
    isSale: false,
    rating: 4.4,
    reviews: 167,
  },
  {
    id: 6,
    name: "Ensemble STWD Brand",
    category: "ensemble",
    price: 125,
    description: "Ensemble STWD brand set. Available in multiple colors.",
    image: cloudinaryImages[5],
    images: [cloudinaryImages[5]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Noir", "Gray Fonce", "Gray"],
    stock: {
      "Noir": 30,
      "Gray Fonce": 30,
      "Gray": 4,
    },
    isNew: false,
    isSale: false,
    rating: 4.6,
    reviews: 245,
  },
  {
    id: 7,
    name: "V2 Nike Short",
    category: "shorts",
    price: 60,
    description: "V2 Nike short. Available in multiple colors.",
    image: cloudinaryImages[6],
    images: [cloudinaryImages[6]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Marron", "Casse", "Gray Clair", "Green", "Blue", "Gray Fonce", "Black"],
    stock: {
      "Marron": 56,
      "Casse": 20,
      "Gray Clair": 20,
      "Green": 24,
      "Blue": 24,
      "Gray Fonce": 100,
      "Black": 100,
    },
    isNew: true,
    isSale: false,
    rating: 4.9,
    reviews: 78,
  },
  {
    id: 8,
    name: "V2 Jordan Shorts",
    category: "shorts",
    price: 60,
    description: "V2 Jordan shorts. Available in multiple colors.",
    image: cloudinaryImages[7],
    images: [cloudinaryImages[7]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Marron", "Casse", "Gray Clair", "Green", "Blue", "Gray Fance", "Black"],
    stock: {
      "Marron": 56,
      "Casse": 20,
      "Gray Clair": 20,
      "Green": 24,
      "Blue": 24,
      "Gray Fance": 100,
      "Black": 100,
    },
    isNew: false,
    isSale: false,
    rating: 4.5,
    reviews: 312,
  },
  {
    id: 9,
    name: "Jordan Short",
    category: "shorts",
    price: 65,
    description: "Jordan short. Available in multiple colors.",
    image: cloudinaryImages[8],
    images: [cloudinaryImages[8]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Green", "Bleu", "Rouge", "Gray Clair", "Mint", "Black", "Marron", "Gray Fonce"],
    stock: {
      "Green": 15,
      "Bleu": 16,
      "Rouge": 16,
      "Gray Clair": 11,
      "Mint": 8,
      "Black": 44,
      "Marron": 11,
      "Gray Fonce": 28,
    },
    isNew: false,
    isSale: false,
    rating: 4.4,
    reviews: 134,
  },
  {
    id: 10,
    name: "Black Short",
    category: "shorts",
    price: 80,
    description: "Premium quality black short. Available in multiple colors.",
    image: cloudinaryImages[0],
    images: [cloudinaryImages[0]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Casse", "Gray Clair", "Gray Fonce", "Vert", "Noir"],
    stock: {
      "Casse": 28,
      "Gray Clair": 40,
      "Gray Fonce": 116,
      "Vert": 36,
      "Noir": 186,
    },
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 45,
  },
  {
    id: 11,
    name: "Nike Short",
    category: "shorts",
    price: 65,
    description: "Nike short with premium quality fabric. Available in multiple colors.",
    image: cloudinaryImages[1],
    images: [cloudinaryImages[1]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Reed", "Green", "Mint", "Marron", "Gray Clair", "Bleu", "Gray Fance", "Noir"],
    stock: {
      "Reed": 36,
      "Green": 28,
      "Mint": 11,
      "Marron": 40,
      "Gray Clair": 32,
      "Bleu": 39,
      "Gray Fance": 71,
      "Noir": 120,
    },
    isNew: true,
    isSale: false,
    rating: 4.2,
    reviews: 98,
  },
  {
    id: 12,
    name: "STWD Shirt",
    category: "shirts",
    price: 70,
    description: "STWD shirt available in blue, green, and brown.",
    image: cloudinaryImages[2],
    images: [cloudinaryImages[2]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Blue", "Green", "Brown"],
    stock: {
      "Blue": 50,
      "Green": 50,
      "Brown": 50,
    },
    isNew: false,
    isSale: false,
    rating: 4.6,
    reviews: 189,
  },
  {
    id: 13,
    name: "STWD Pants",
    category: "pants",
    price: 80,
    description: "STWD pants with premium quality. Available in multiple colors.",
    image: cloudinaryImages[3],
    images: [cloudinaryImages[3]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "Gray Clair", "Vert", "Marron", "Gray Fance"],
    stock: {
      "Black": 60,
      "Gray Clair": 60,
      "Vert": 24,
      "Marron": 30,
      "Gray Fance": 30,
    },
    isNew: false,
    isSale: false,
    rating: 4.3,
    reviews: 67,
  },
  {
    id: 14,
    name: "Green Short",
    category: "shorts",
    price: 80,
    description: "Green short in stock. Available in multiple colors.",
    image: cloudinaryImages[4],
    images: [cloudinaryImages[4]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Reed", "Gray Fonce", "Casse", "Noir"],
    stock: {
      "Reed": 36,
      "Gray Fonce": 144,
      "Casse": 40,
      "Noir": 116,
    },
    isNew: true,
    isSale: false,
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 15,
    name: "Ensemble STWD Brand",
    category: "ensemble",
    price: 125,
    description: "Ensemble STWD brand set. Available in multiple colors.",
    image: cloudinaryImages[5],
    images: [cloudinaryImages[5]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Noir", "Gray Fonce", "Gray"],
    stock: {
      "Noir": 30,
      "Gray Fonce": 30,
      "Gray": 4,
    },
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviews: 112,
  },
  {
    id: 16,
    name: "V2 Nike Short",
    category: "shorts",
    price: 60,
    description: "V2 Nike short. Available in multiple colors.",
    image: cloudinaryImages[6],
    images: [cloudinaryImages[6]],
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Marron", "Casse", "Gray Clair", "Green", "Blue", "Gray Fonce", "Black"],
    stock: {
      "Marron": 56,
      "Casse": 20,
      "Gray Clair": 20,
      "Green": 24,
      "Blue": 24,
      "Gray Fonce": 100,
      "Black": 100,
    },
    isNew: false,
    isSale: false,
    rating: 4.5,
    reviews: 423,
  },
];

export const categories = [
  { id: "all", name: "All", image: "https://picsum.photos/seed/all/600/400" },
  { id: "shorts", name: "Shorts", image: "https://picsum.photos/seed/shorts/600/400" },
  { id: "shirts", name: "Shirts", image: "https://picsum.photos/seed/shirts/600/400" },
  { id: "pants", name: "Pants", image: "https://picsum.photos/seed/pants/600/400" },
  { id: "ensemble", name: "Ensemble", image: "https://picsum.photos/seed/ensemble/600/400" },
];

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all" || !category) return products;
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isNew || p.isSale).slice(0, 8);
}